{% set name = "nbtutor" %}
{% set version = "2.0.2" %}
{% set sha256 = "fc234bd241c3e3d5560b5379d790fe53181e6ad7f3e706b0cb7f46449381bdf1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - notebook
    - pip

  run:
    - python >=3.6
    - notebook

test:
  imports:
    - nbtutor

  requires:
    - pip

  commands:
    - pip check

about:
  home: https://github.com/lgpage/nbtutor
  summary: Visualize Python code execution in Jupyter Notebook cells
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE.md
  dev_url: https://github.com/lgpage/nbtutor

extra:
  recipe-maintainers:
    - lgpage
