{% set gh_org = "lgpage" %}
{% set gh_repo = "nbtutor" %}
{% set version = "1.0.4" %}
{% set sha256 = "64d8f3ecccd77b16086710cd2dac8f2c0c1aef77916862770b7e948af9e05716" %}

package:
  name: {{ gh_repo|lower }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

requirements:
  build:
    - nodejs
    - notebook >=4.2.0
    - python
    - setuptools

  run:
    - notebook >=4.2.0
    - python

test:
  requires:
    - coverage
    - nodejs
    - notebook >=4.2.0
    - pytest
    - pytest-cov
    - python
    - requests

  imports:
    - nbtutor

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE.rst
  summary: Visualize Python code execution in Jupyter Notebook cells

extra:
  recipe-maintainers:
    - lgpage
