appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FzMhe5u+sZvIvD/tk/39vB1og1ojPNfIUzbeuexMdoSs96GsXUTZp+isoTgSY43r9uKDMRMXJ8mtUeRvwKyw6p+rYythFR8ubIStmP3+cN6QT4LOpJ2V7sSjIY1egDAFcllNwR5s1gu3wI5i31OtrwCVNVpsP77YtVqKgZIBYblDVd1ORd5fRiyspVTaEe+HZIzM/Ik4JWYWUsP9ZeFjvCQFMgLfwAWCzpzY8/9PKjKcxTsYeACHhcmZHov4QjpsoG9euyRIb0e2DmA4mbopv6IYqlxg9rPfIcbhGN9G8zTDbX5rNJ0Ds9V1lLEk26cVDU1I/vOCIHDSRjK67Ni5gfmbPSzq2WaKjwDPWEFSyh9jTHncJ4QWl/8v/ngcrhpH2H1lu/RF9Fa1fI0jqnW60yhaXfdK7WNZ/+BPndALrKKRvudgyPDXgeKYm329prQozJvLPE34PMqMjdi9U2O1e6My6ohpSsLWdcb5NecTSSse/wmYT7q2LMZbn3NNO1D7/pnhYsp2NdWMCmEbMEK46DGajH/k9Opfp25iYTYvzGH2+mQK2Xpi4K01bWV/roySqREAWMCIV5xKId/g3YgpQ+7APlut37kH0BATqy0h4UpBQO+FV0i1pY5or9/WE+9oq1X6N4iZ0WBknvw0Bfuj5m4DQeTHVgYXa+DagoER8EE=}
