travis:
  secure:
    BINSTAR_TOKEN: eT8Nv0WtwHBvqXz5cyhCZfG49jvUKm/uSLJKfyFansKZq0iR5QLZj7HAZSXFSe0oE0R+BQvIJ1GVksAHHVhEQoRJlY2rDpSkLBEJ/O4N6wGArEhvdMHbM9R9Sf88KIlwwsZYY0qTvIMZ/NUlRogJyL5lSS4AVb9UZ1BaJHSBam8ZwGWwPUeHuChQ6QcmnzbQVcPH0CD9Cd5kSE8yQn/ksKRU1aLHshEEX+/uhdWleLRMK3gXQYfiDJGc5u0EwVbKMfNj+yvy6Qkv0yA18PbJc8PwdLI43WdtiL6VgOtXOFniW8d0kEeYECEZa2hF2X6h3oFVAmwSLqBCIP8MUt/xC9h2GfZBAoFq8lWcURH4dZkEfb41IKInlgua8ITwJUHyMNDPlzcV0MfMU5DWzI52JX5beAMSMbG+IfJIZ5k3KCMpiuc2FeoiWaBEIanaEZafDrRaOPrSH6lMMUycM7LLPd7JDq53HRDDXFjGWep72wULPTcIezTzLPGfBXPxiqI39vQLpwfN1nhJUfl0OGWE/5nNt5MN63DPF53pwWy9NUF1sa8sFZovLxsrdceAug6zLVD2jBFr9lpGDw4grTofT04chmkuFn4oh0/6d49OKqHgdgDfTaMSHRq28NT4BLSJ3XMB7hBp/zepzrTVQMitgYqnm8V+sLOMSLm7MlJgZNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
